"""add onu_devices table

Revision ID: 0aff9f6c9542
Revises: 808315bf46fd
Create Date: 2026-07-27 12:10:59.203303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aff9f6c9542'
down_revision = '0241c5be677e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onu_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('serial_number_2', sa.String(length=100), nullable=True),
    sa.Column('property_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False, server_default='active'),
    sa.Column('condition', sa.String(length=100), nullable=False, server_default='working'),
    sa.Column('site_id', sa.String(length=255), nullable=True),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('date_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_code'),
    sa.UniqueConstraint('serial_number'),
    sa.UniqueConstraint('serial_number_2')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onu_devices')
    # ### end Alembic commands ###
