"""check drift after inet cidr fix

Revision ID: 6f94455d0318
Revises: b4bad40e219f
Create Date: 2026-07-10 11:44:43.887393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f94455d0318'
down_revision = 'b4bad40e219f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ip_pool_id'), 'ip_pool', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ip_pool_id'), table_name='ip_pool')
    # ### end Alembic commands ###
