"""add olt table

Revision ID: 808315bf46fd
Revises: 0241c5be677e
Create Date: 2026-07-13 11:57:58.949797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808315bf46fd'
down_revision = '0241c5be677e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('olts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('olt_id', sa.Integer(), nullable=False),
    sa.Column('mikrotik_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(
        ['mikrotik_id'],
        ['devices.id'],
        name='fk_olts_mikrotik_id'
    ),
    sa.ForeignKeyConstraint(
        ['olt_id'],
        ['devices.id'],
        name='fk_olts_olt_id'
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('olt_id', 'mikrotik_id', name='uq_olt_mikrotik_mapping')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('olts')
    # ### end Alembic commands ###
