"""Add PPPoE accounting requests table

Revision ID: 93be8f8d6ecf
Revises: add_is_overdue
Create Date: 2025-11-07 16:47:33.282915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93be8f8d6ecf'
down_revision = 'add_is_overdue'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pppoe_accounting_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('framed_protocol', sa.String(length=50), nullable=True),
    sa.Column('nas_port', sa.BigInteger(), nullable=True),
    sa.Column('nas_port_type', sa.String(length=50), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('calling_station_id', sa.String(length=100), nullable=True),
    sa.Column('called_station_id', sa.String(length=255), nullable=True),
    sa.Column('nas_port_id', sa.String(length=255), nullable=True),
    sa.Column('acct_session_id', sa.String(length=255), nullable=False),
    sa.Column('framed_ip_address', sa.String(length=45), nullable=True),
    sa.Column('acct_authentic', sa.String(length=50), nullable=True),
    sa.Column('event_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('acct_status_type', sa.String(length=50), nullable=True),
    sa.Column('nas_identifier', sa.String(length=255), nullable=True),
    sa.Column('acct_delay_time', sa.Integer(), nullable=True),
    sa.Column('nas_ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pppoe_accounting_requests_acct_session_id'), 'pppoe_accounting_requests', ['acct_session_id'], unique=False)
    op.create_index(op.f('ix_pppoe_accounting_requests_calling_station_id'), 'pppoe_accounting_requests', ['calling_station_id'], unique=False)
    op.create_index(op.f('ix_pppoe_accounting_requests_framed_ip_address'), 'pppoe_accounting_requests', ['framed_ip_address'], unique=False)
    op.create_index(op.f('ix_pppoe_accounting_requests_id'), 'pppoe_accounting_requests', ['id'], unique=False)
    op.create_index(op.f('ix_pppoe_accounting_requests_nas_ip_address'), 'pppoe_accounting_requests', ['nas_ip_address'], unique=False)
    op.create_index(op.f('ix_pppoe_accounting_requests_user_name'), 'pppoe_accounting_requests', ['user_name'], unique=False)
    op.drop_index('ix_devices_name', table_name='devices')
    op.create_unique_constraint(None, 'devices', ['name'])
    op.drop_index('ix_onus_serial_no', table_name='onus')
    op.create_unique_constraint(None, 'onus', ['serial_no'])
    op.alter_column('pppoe_users', 'service_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Framed-User'::character varying"))
    op.alter_column('pppoe_users', 'framed_protocol',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'PPP'::character varying"))
    op.alter_column('pppoe_users', 'mikrotik_rate_limit',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'5M/5M'::character varying"))
    op.alter_column('pppoe_users', 'mikrotik_recv_limit_gigawords',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pppoe_users', 'mikrotik_xmit_limit_gigawords',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pppoe_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('pppoe_users', 'is_overdue',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pppoe_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pppoe_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pppoe_users', 'is_overdue',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('pppoe_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('pppoe_users', 'mikrotik_xmit_limit_gigawords',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pppoe_users', 'mikrotik_recv_limit_gigawords',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('pppoe_users', 'mikrotik_rate_limit',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'5M/5M'::character varying"))
    op.alter_column('pppoe_users', 'framed_protocol',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'PPP'::character varying"))
    op.alter_column('pppoe_users', 'service_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Framed-User'::character varying"))
    op.drop_constraint(None, 'onus', type_='unique')
    op.create_index('ix_onus_serial_no', 'onus', ['serial_no'], unique=False)
    op.drop_constraint(None, 'devices', type_='unique')
    op.create_index('ix_devices_name', 'devices', ['name'], unique=False)
    op.drop_index(op.f('ix_pppoe_accounting_requests_user_name'), table_name='pppoe_accounting_requests')
    op.drop_index(op.f('ix_pppoe_accounting_requests_nas_ip_address'), table_name='pppoe_accounting_requests')
    op.drop_index(op.f('ix_pppoe_accounting_requests_id'), table_name='pppoe_accounting_requests')
    op.drop_index(op.f('ix_pppoe_accounting_requests_framed_ip_address'), table_name='pppoe_accounting_requests')
    op.drop_index(op.f('ix_pppoe_accounting_requests_calling_station_id'), table_name='pppoe_accounting_requests')
    op.drop_index(op.f('ix_pppoe_accounting_requests_acct_session_id'), table_name='pppoe_accounting_requests')
    op.drop_table('pppoe_accounting_requests')
    # ### end Alembic commands ###
